/// Execution modes governing the privacy boundary.
enum ExecutionMode {
  privateOffline,
  hybrid,
  cloud;

  String toJson() {
    switch (this) {
      case ExecutionMode.privateOffline:
        return 'private_offline';
      case ExecutionMode.hybrid:
        return 'hybrid';
      case ExecutionMode.cloud:
        return 'cloud';
    }
  }

  static ExecutionMode fromJson(String value) {
    switch (value) {
      case 'private_offline':
        return ExecutionMode.privateOffline;
      case 'hybrid':
        return ExecutionMode.hybrid;
      case 'cloud':
        return ExecutionMode.cloud;
      default:
        return ExecutionMode.privateOffline;
    }
  }
}

/// Application mode tailoring the UX and extraction intelligence.
enum ApplicationMode {
  general,
  interviewPractice,
  meeting,
  education,
  travel;

  String toJson() {
    switch (this) {
      case ApplicationMode.general:
        return 'general';
      case ApplicationMode.interviewPractice:
        return 'interview_practice';
      case ApplicationMode.meeting:
        return 'meeting';
      case ApplicationMode.education:
        return 'education';
      case ApplicationMode.travel:
        return 'travel';
    }
  }

  static ApplicationMode fromJson(String value) {
    switch (value) {
      case 'general':
        return ApplicationMode.general;
      case 'interview_practice':
        return ApplicationMode.interviewPractice;
      case 'meeting':
        return ApplicationMode.meeting;
      case 'education':
        return ApplicationMode.education;
      case 'travel':
        return ApplicationMode.travel;
      default:
        return ApplicationMode.general;
    }
  }
}

/// The 7 distinct personas for multi-perspective explanations.
enum ExplanationPersona {
  simple,
  detailed,
  terminology,
  grammar,
  culturalContext,
  examples,
  childFriendly;

  String toJson() {
    switch (this) {
      case ExplanationPersona.simple:
        return 'simple';
      case ExplanationPersona.detailed:
        return 'detailed';
      case ExplanationPersona.terminology:
        return 'terminology';
      case ExplanationPersona.grammar:
        return 'grammar';
      case ExplanationPersona.culturalContext:
        return 'cultural_context';
      case ExplanationPersona.examples:
        return 'examples';
      case ExplanationPersona.childFriendly:
        return 'child_friendly';
    }
  }

  static ExplanationPersona fromJson(String value) {
    switch (value) {
      case 'simple':
        return ExplanationPersona.simple;
      case 'detailed':
        return ExplanationPersona.detailed;
      case 'terminology':
        return ExplanationPersona.terminology;
      case 'grammar':
        return ExplanationPersona.grammar;
      case 'cultural_context':
        return ExplanationPersona.culturalContext;
      case 'examples':
        return ExplanationPersona.examples;
      case 'child_friendly':
        return ExplanationPersona.childFriendly;
      default:
        return ExplanationPersona.simple;
    }
  }
}

/// Real-time conversation state machine.
enum ConversationState {
  idle,
  listening,
  transcribing,
  translating,
  ready,
  speaking;

  String toJson() => name.toUpperCase();

  static ConversationState fromJson(String value) {
    return ConversationState.values.firstWhere(
      (e) => e.name.toUpperCase() == value.toUpperCase(),
      orElse: () => ConversationState.idle,
    );
  }
}

/// Report types generated by the reporting engine.
enum ReportType {
  quickSummary,
  detailedSummary,
  fullTranscript,
  questionsReport,
  learningReport,
  actionItems,
  meetingMinutes,
  interviewReport,
  vocabularyReport;

  String toJson() {
    switch (this) {
      case ReportType.quickSummary:
        return 'quick_summary';
      case ReportType.detailedSummary:
        return 'detailed_summary';
      case ReportType.fullTranscript:
        return 'full_transcript';
      case ReportType.questionsReport:
        return 'questions_report';
      case ReportType.learningReport:
        return 'learning_report';
      case ReportType.actionItems:
        return 'action_items';
      case ReportType.meetingMinutes:
        return 'meeting_minutes';
      case ReportType.interviewReport:
        return 'interview_report';
      case ReportType.vocabularyReport:
        return 'vocabulary_report';
    }
  }

  static ReportType fromJson(String value) {
    switch (value) {
      case 'quick_summary':
        return ReportType.quickSummary;
      case 'detailed_summary':
        return ReportType.detailedSummary;
      case 'full_transcript':
        return ReportType.fullTranscript;
      case 'questions_report':
        return ReportType.questionsReport;
      case 'learning_report':
        return ReportType.learningReport;
      case 'action_items':
        return ReportType.actionItems;
      case 'meeting_minutes':
        return ReportType.meetingMinutes;
      case 'interview_report':
        return ReportType.interviewReport;
      case 'vocabulary_report':
        return ReportType.vocabularyReport;
      default:
        return ReportType.quickSummary;
    }
  }
}
